Seperate relayer instance in integration tests
AdExNetwork/adex-market pull request #152
Opened 2020-08-06 13:43 UTC by simzzz

2020-08-07 11:11 UTC, samparsky commented
@simzzz Does this enable us to run the commented out integration tests? i.e. `postMedia` etc

2020-08-07 13:26 UTC, simzzz commented
> @simzzz Does this enable us to run the commented out integration tests? i.e. `postMedia` etc

Our IPFS node is IP whitelisted, which makes the tests unreliable. That's why I commented out the tests that use it.

2021-03-10 21:59 UTC, Ivshti requested changes
Looks good except one missed thing which might break things @simzzz

2021-03-10 21:59 UTC, Ivshti commented on routes/adSlots.js
> -async function getTargetingData(req, res) {
not sure this line would work without `req, `

2021-03-11 10:41 UTC, merged