Bigquery add adunits and targeting
AdExNetwork/adex-market pull request #159
Opened 2020-09-04 11:29 UTC by rori4

This adds AdUnits and Audiences so Galya can display them in the Data Studio report.

I only have a few questions on this. 

Do all campaigns right now have audience attached to it? If yes then this should be OK

2020-09-04 11:32 UTC, Ivshti commented
@rori4 regarding whether all campaigns have audiences, @IvoPaunov can tell you

2020-09-16 08:32 UTC, rori4 commented
needs some changes as discussed on slack

2020-09-25 13:29 UTC, IvoPaunov commented on scripts/bigquery.js
> +			.find()
Cant you add filter `{campaignId: { $exists: true, $ne: null }}` instead `if (!campaign) return // skip if not used in campaign`

2020-09-25 13:33 UTC, IvoPaunov requested changes
just fix the audience filter

2020-09-25 14:24 UTC, IvoPaunov approved these changes

2020-10-13 08:14 UTC, merged